import Head from "next/head";
import { Heading, Flex,VStack } from "@chakra-ui/react";

//Component
import Navebar from "@/component/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Perfect Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <VStack spacing={2}>
          <Navebar/>
        </VStack>
      </main>
    </>
  );
}